### ISSUE TITLE
onic_main.c: netdev_stats missing __percpu annotation breaks build on kernel 6.18 / GCC 15

### ISSUE THREAD

**Issue by marcfiu** [foucast/open-nic-driver#1]
## Summary

Building the driver against Linux kernel **6.18.0** with **GCC 15.2.0** (the exact compiler the 6.18.0 mainline PPA kernel was built with) fails:

```
onic_main.c: In function 'onic_probe':
onic_main.c:236:28: error: assignment from pointer to non-enclosed address space
  236 |         priv->netdev_stats = alloc_percpu(struct rtnl_link_stats64);
      |                            ^
onic_main.c:236:28: note: expected 'struct rtnl_link_stats64 *' but pointer is of type '__seg_gs struct rtnl_link_stats64 *'
```

## Root cause

`onic.h` declares the per-cpu stats pointer without the `__percpu` annotation:

```c
struct rtnl_link_stats64 *netdev_stats;
```

`alloc_percpu()` returns a `__percpu`-qualified pointer. Historically this mismatch was only caught by `sparse` (`make C=1`), since `__percpu` was just a `sparse` no-op annotation for plain GCC/Clang builds. As of **GCC 15**, `__percpu` is treated as a genuine named address space (`__seg_gs`) rather than ignored, so a plain (non-sparse) build now fails outright with `-Werror` (which this driver's Makefile sets).

## Fix

Add the missing annotation:

```c
struct rtnl_link_stats64 __percpu *netdev_stats;
```

Verified: driver builds clean (`onic.ko`) against `linux-headers-6.18.0-061800-generic` (Ubuntu mainline PPA build) with `gcc-15 (Ubuntu 15.2.0-4ubuntu4)`, no other source changes needed.

## Notes

- This repo is a fork of the (apparently no-longer-maintained) `Xilinx/open-nic-driver`. Filing this here rather than upstream so we have a record of local deltas that should be contributed back if `Xilinx/open-nic-driver` (or a successor) ever resumes maintenance.
- Tested on kernel headers only (no OpenNIC hardware present in the environment the fix was validated in) — build success confirmed, hardware load/runtime test still pending on an actual SB9 node once one is upgraded to 6.18.
